# Generated by Django 5.1.1 on 2024-09-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_menuitem_img_menuitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
