# Generated by Django 5.1.1 on 2024-09-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('sushi_roll', 'Sushi Roll'), ('main_course', 'Main Course'), ('drink', 'Drink')], default='starter', max_length=50),
        ),
    ]
