# Generated by Django 5.1.1 on 2024-10-02 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.menuitem')),
                ('shopping_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shoppingbox')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingbox',
            name='items',
            field=models.ManyToManyField(through='accounts.ShoppingBoxItem', to='accounts.menuitem'),
        ),
    ]
