# Generated by Django 5.1.1 on 2024-10-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_shoppingbox_shoppingboxitem_shoppingbox_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingboxitem',
            name='shopping_box',
        ),
        migrations.RemoveField(
            model_name='shoppingboxitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='ShoppingBox',
        ),
        migrations.DeleteModel(
            name='ShoppingBoxItem',
        ),
    ]
